### ISSUE TITLE
The Download button for Android Studio plugin has disappeared

### ISSUE THREAD

**Issue by skwokmag** [magnetsystems/rest2mobile#15]
Priority: Blocker
There was a button on http://developer.magnet.com/android/?dl=1 for developers to download the Android Studio plugin and it has disappeared.

**Comment by etexier** [comment]
I think @vampserv owns the landing page on the developer factory.

**Comment by skwokmag** [comment]
Thank you, @etexier. This has been resolved.

**Comment by vampserv** [comment]
@pjaillon I suggest we remove the behavior to hide the download button if download was triggered automatically.

**Comment by pjaillon** [comment]
The expected behavior is the following:

From the landing page (http://developer.magnet.com/):
1. if a user clicks on Android, iOS and JS icon, the user is redirected to the next page and the download is automatically triggered. As a result, the download icon does not show up on the page.
2. if a user clicks on one of the "Learn More" links, the user is redirected to the next page. An icon then appears, on the top-right corner, to let the developer trigger the download when ready.
